name: Java CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17
    - name: Build with Gradle
      run: ./gradlew :distribution:archives:linux-tar:assemble

